package rbacprofile

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite the generated RBAC manifests")

// generated maps each committed file to the function that produces it. This is
// the whole drift guard: the same map both writes the files under -update and
// asserts them without it, so the generator and the assertion can never disagree.
func generated() map[string]string {
	out := map[string]string{
		filepath.Join("..", "..", "deploy", "rbac.yaml"):                                          RenderBaseManifest(),
		filepath.Join("..", "..", "deploy", "helm", "kubeagent", "templates", "clusterrole.yaml"): RenderHelmClusterRole(),
	}
	for _, f := range Features() {
		if f.Manifest == "" || f.Name == "core" {
			continue
		}
		out[filepath.Join("..", "..", "deploy", f.Manifest)] = RenderAddonManifest(f)
	}
	return out
}

func TestGeneratedManifests(t *testing.T) {
	for path, want := range generated() {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatalf("writing %s: %v", path, err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("reading %s: %v", path, err)
			continue
		}
		if !bytes.Equal(got, []byte(want)) {
			t.Errorf("%s is out of date with internal/rbacprofile.\n%s\n\nRegenerate: go test ./internal/rbacprofile -run TestGeneratedManifests -update",
				path, firstDiff(string(got), string(want)))
		}
	}
}

// Deleting a feature row must not leave an orphaned manifest applying grants
// nothing in the table justifies.
func TestNoOrphanedManifests(t *testing.T) {
	onDisk, err := filepath.Glob(filepath.Join("..", "..", "deploy", "rbac-*.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	claimed := generated()
	for _, path := range onDisk {
		if _, ok := claimed[path]; !ok {
			t.Errorf("%s is not generated by any feature in the table", path)
		}
	}
}

// firstDiff reports the first differing line, so a failure names the drift
// instead of dumping two whole manifests.
func firstDiff(got, want string) string {
	g, w := strings.Split(got, "\n"), strings.Split(want, "\n")
	for i := 0; i < len(g) || i < len(w); i++ {
		var gl, wl string
		if i < len(g) {
			gl = g[i]
		}
		if i < len(w) {
			wl = w[i]
		}
		if gl != wl {
			return "first difference at line " + strconv.Itoa(i+1) + ":\n  on disk:   " + gl + "\n  generated: " + wl
		}
	}
	return "files differ only in trailing bytes"
}
